name: ucum
description: Dart Library Mimicking the Unified Code for Units of Measure Library Functionality
version: 0.7.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/ucum

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  xml: ^6.6.1

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
